[package]
name = "shortwave"
version = "0.1.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
edition = "2018"

[dependencies]
gtk = { version = "0.7.0", features = ["v3_22"] }
libhandy = "0.4.0"
glib = { version = "0.8.1", features = ["subclassing"] }
gobject-sys = "0.9.0"
glib-sys = "0.9.0"
gio = { version = "0.7.0", features = ["v2_46"] }
gdk = "0.11.0"
gdk-pixbuf = { version = "0.7.0", features = ["futures"] }
gstreamer = "0.14.5"
gstreamer-pbutils = "0.14.0"
mpris-player = "0.4.0"
log = "0.4.7"
pretty_env_logger = "0.3.0"
quick-error = "1.2.2"
restson = "0.5.4"
uuid = { version = "0.7.4", features = ["v4"] }
chrono = "0.4.7"
rust_cast = "0.14.0"
mdns = "0.3.1"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
lazy_static = "1.3.0"
matches = "0.1.8"
open = "1.2.3"
serde_urlencoded = "0.5.5"
url = "2.0.0"
diesel = { version = "1.4.2", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4.0"
xdg = "2.2.0"
soup = { git="https://gitlab.gnome.org/haecker-felix/soup-rs", features = ["futures"] }
indexmap = { git = "https://github.com/bluss/indexmap.git", rev = "380e55c6a330b03f554f59ebd01c075bf396dd47" }
gettext-rs= { version = "0.4", features = ["gettext-system"] }
failure = "0.1.5"
failure_derive = "0.1.5"
