[package]
name = "shortwave"
version = "0.0.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4"
chrono = "0.4.11"
rust_cast = "0.15"
mdns = "0.3.1"
serde = "1.0.114"
serde_json = "1.0.55"
serde_derive = "1.0.114"
serde_urlencoded = "0.6.1"
lazy_static = "1.4.0"
matches = "0.1.8"
open = "1.4.0"
url = "2.1.0"
indexmap = "1.4.0"
strum = "0.19"
strum_macros = "0.19"
diesel_migrations = "1.4.0"
diesel = { version = "1.4.3", features = ["sqlite", "r2d2"] }
futures = "0.3.5"
futures-io = "0.3.5"
futures-util = "0.3.5"
async-std = "1.6.2"
isahc = {version = "0.9", features = ["json"]}
regex = "1.3.9"
thiserror = "1.0"

gstreamer-audio = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", features = ["v1_10"] }
gstreamer = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
gettext-rs = { version = "0.4.4", features = ["gettext-system"] }
gtk-macros = "0.2.0"

[target.'cfg(unix)'.dependencies]
mpris-player = "0.6.0"

[dependencies.cairo]
git = "https://github.com/gtk-rs/gtk-rs/"
package = "cairo-rs"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs/"
features = ["v2_64"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gtk4"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gtk4-rs/"
package = "gdk4"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gtk-rs/"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs/"
features = ["v2_64"]

[dependencies.libhandy]
git = "https://gitlab.gnome.org/bilelmoussaoui/libhandy4-rs"
package = "libhandy4"
