[package]
name = "shortwave"
version = "0.1.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
build = "build.rs"
edition = "2018"

[dependencies]
gio = "0.5"
glib = "0.6.1"
gdk = "0.9.0"
log = "0.4"
simplelog = "0.5"
rustio = { git="https://github.com/haecker-felix/Rustio.git" }
gstreamer = "0.12"
gstreamer-pbutils = "0.12"
mpris-player = "0.1"
rusqlite = "0.13"
indexmap = "1.0"
quick-error = "1.2.2"
restson = "0.4"
stopwatch = "0.0.7"
uuid = { version = "0.7", features = ["v4"] }

[dependencies.gtk]
version = "0.5"
features = ["v3_22"]

[dependencies.libhandy]
git = "https://gitlab.gnome.org/World/Rust/libhandy-rs"
features = ["v0_0_6"]
