[package]
name = "shortwave"
version = "0.0.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
edition = "2018"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.3.1"
quick-error = "1.2.2"
restson = "0.5.4"
chrono = "0.4.9"
rust_cast = "0.14.0"
mdns = "0.3.1"
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.102"
serde_urlencoded = "0.6.1"
lazy_static = "1.4.0"
matches = "0.1.8"
open = "1.3.2"
url = "2.1.0"
xdg = "2.2.0"
indexmap = "1.3.0"
failure = "0.1.6"
failure_derive = "0.1.6"
strum = "0.16.0"
strum_macros = "0.16.0"
mpris-player = "0.4.0"
cairo-rs = "0.7.1"
gdk = "0.11.0"
gstreamer = "0.14.5"
diesel_migrations = "1.4.0"
diesel = { version = "1.4.3", features = ["sqlite", "r2d2"] }
gtk = { version = "0.7.0", features = ["v3_22"] }
gio = { version = "0.7.0", features = ["v2_46"] }
glib = { version = "0.8.2", features = ["subclassing"] }
gdk-pixbuf = { version = "0.7.0", features = ["futures", "v2_36"] }
gettext-rs = { version = "0.4.4", features = ["gettext-system"] }
libhandy = { git="https://gitlab.gnome.org/haecker-felix/libhandy-rs.git" }
soup = { git="https://gitlab.gnome.org/haecker-felix/soup-rs", features = ["futures"] }
